# Generated by Django 2.2.5 on 2019-09-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
